### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by sweetpineapple** [qiyeboy/IPProxys#3]
我运行一段时间（好多天）之后，出现下面的错误，能不能帮忙看一看
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "IPProxys.py", line 30, in startSpider
    spider.run()
  File "E:\python\IPProxys\spider\ProxySpider.py", line 35, in run
    proxys = self.crawl_pool.map(self.crawl,parserList)
  File "C:\Anaconda2\lib\site-packages\gevent\pool.py", line 308, in map
    return list(self.imap(func, iterable))
  File "C:\Anaconda2\lib\site-packages\gevent\pool.py", line 102, in next
    raise value.exc
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by qiyeboy** [comment]
找到问题了，由于代理网站增加了反爬虫机制，导致解析出现bug,已经修复
